spring:
  # 文件上传大小限制
  servlet:
    multipart:
      # 单个文件最大限制
      max-file-size: 5MB
      # 单次请求文件最大限制
      max-request-size: 5MB
  # 配置路径匹配策略为ant风格
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# 配置七牛云OSS对象存储
oss:
  # 配置AK
  accessKey: IkpGPlDZBWx9IppOrhrzRs1U9bVqWP2OvgaIMjwI
  # 配置SK
  secretKey: 4zMtIlfDE9AQYXM2nPnCey4zuSP_x5yyvHWxUl2K
  # 配置桶
  bucket: bbs-school-system
  # 配置基础域名
  baseUrl: http://www.qinyc.xyz/